services:
  mongo:
    image: mongo:latest
    container_name: mongao
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    networks:
      - my-local-network

  app1:
    build: .
    container_name: app1
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - mongo
    environment:
      MONGODB_URI: mongodb://admin:admin123@mongo:27017/mydb?authSource=admin
    networks:
      - my-local-network

  app2:
    build: .
    container_name: app2
    restart: always
    ports:
      - "8082:8080"
    depends_on:
      - mongo
    environment:
      MONGODB_URI: mongodb://admin:admin123@mongo:27017/mydb?authSource=admin
    networks:
      - my-local-network

  nginx:
    image: nginx:latest
    container_name: nginxao
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - app1
      - app2
    networks:
      - my-local-network

networks:
  my-local-network:
    driver: bridge